### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by PUDGE133** [Jesus-QC/BanLogger#1]
![110232767-e447ca80-7f30-11eb-8d0c-d84c6118491f](https://user-images.githubusercontent.com/47304666/111122903-be00db00-857f-11eb-89be-31db133f4ef1.png)
```yaml
BanLogger:
# Is the plugin enabled?
  is_enabled: true
  public_webhook_url: https://discord.com/api/webhooks/webhook.id/webhook.token
  security_webhook_url: MY WEBHOOK LINK
  # Steam Api key to get the nickname of obanned users (Get your api key in https://steamcommunity.com/dev/apikey)
  steam_api_key: MY STEAM API KEY
  # Webhook Username
  username: MyServer Bans | Security
  # Webhook avatar image
  avatar_url: https://imgur.com/FpPpR90.png
  # Content out of the embed, you can for example ping a role
  content: <@&811252527398912059>
  # Is TTS enabled?
  is_tts_enabled: false
  # Hex Color of the webhook
  hex_color: '#D10E11'
  # Webhook author name depending of the port of the server
  server_name:
    7777: 'MyServer #1 | Security'
    7778: 'MyServer #2 | Security'
    7779: 'MyServer #3 | Security'
  # Webhook author image URL (server image)
  server_img_url: https://imgur.com/FpPpR90.png
  # Title of the embed
  title: ЛОГГЕР БАНОВ И КИКОВ
  # Default: User banned:
  user_banned_text: 'Забанен пользователь:'
  # Default: Issuing staff:
  issuing_staff_text: 'Админ который выдал бан:'
  # Default: Reason:
  reason_text: 'Причина:'
  # Default: Time banned:
  time_banned_text: 'Забанен на:'
  # Webhook image URL
  image_url: https://imgur.com/spXs9Bq.png
  # Footer Text
  footer_txt: ''
  # Footer IconUrl
  footer_icon_url: ''
```
