### ISSUE TITLE
No message or log

### ISSUE THREAD

**Issue by BoozyAF** [Jesus-QC/BanLogger#8]
Console is empty, but the plugin has been loaded. Changed the config to use my webhook and steamapi, but still no message.
I might be dumb but this also might be an issue.

Here is my config file:

```
BanLogger:
# Is the plugin enabled?
  is_enabled: true
  # Public Webhooks (Mute/Kick/Ban/OBan)
  public_webhooks: My webhook URL here
    Kick: https://discord.com/api/webhooks/webhook.id/webhook.token
    OBan: https://discord.com/api/webhooks/webhook.id/webhook.token
  # Private Webhooks (Mute/Kick/Ban/OBan) Contains IDs and more info
  private_webhooks: My webhook URL here
    Mute: https://discord.com/api/webhooks/webhook.id/webhook.token
    Ban: https://discord.com/api/webhooks/webhook.id/webhook.token
  # Steam Api key to get the nickname of obanned users (Get your api key in https://steamcommunity.com/dev/apikey)
  steam_api_key: My Steam API key here
  # Webhook Username
  username: Ban Logs
  # Webhook avatar image
  avatar_url: https://imgur.com/FpPpR90.png
  # Content out of the embed, you can for example ping a role
  content: ''
  # Is TTS enabled?
  is_tts_enabled: false
  # Hex Color of the webhook
  hex_color: '#D10E11'
  # Webhook author name depending of the port of the server
  author_name: 'Server name here'
  # Webhook author image URL (server image)
  server_img_url: https://imgur.com/FpPpR90.png
  # Title of the embed
  title: BAN & KICK LOGGER
  # Default: User banned:
  user_banned_text: 'User:'
  # Default: Issuing staff:
  issuing_staff_text: 'Issuing staff:'
  # Default: Reason:
  reason_text: 'Reason:'
  # Default: Time banned:
  time_banned_text: 'Time banned:'
  # Webhook image URL
  image_url: https://imgur.com/spXs9Bq.png
  # Footer Text
  footer_txt: ''
  # Footer IconUrl
  footer_icon_url: ''
```
